- name: Install and start Nginx
  hosts: frontend
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Start Nginx service
      service: # we can use ansible.builtin.service module.
        name: nginx
        state: started
        enabled: yes
