- name: Data Types
  hosts: localhost
  connection: local # skips the SSH connection (which require credentials) and runs the playbook on the local machine.
  vars:
    name: "John Wick" # String
    age: 45 # Integer
    height: 6.1 # Float
    is_married: no # Boolean Yes and No or True or False
    spouse: # null value
    skills:
      - Python
      - Ansible
      - Linux # List
    address:
      street: "123 Main St"
      city: "New York"
      state: "NY" # Dictionary (Map)
  tasks:
    - name: Printing Variables
      debug:
        msg: |
          name: {{ name }}
          age: {{ age }}
          height: {{ height }}
          is_married: {{ is_married }}
          spouse: {{ spouse }}
          skills: {{ skills[0] }}
          address: {{ address.city }}
