- name: Variables from file
  hosts: localhost
  connection: local
  vars_files:
    - variables.yml
  tasks:
    - name: Show variable value from file
      debug:
        msg: "{{ name }}" # name is a variable defined in the variables.yml file.
