;[ungrouped]
169.256.169.256

[ungrouped:vars]
my_name = "John Wick from inventory.ini ungrouped group"

[all:vars]
my_name = "John Wick from inventory.ini all group"

[frontend]
    34.226.193.201

[backend]
    34.226.193.202

[project:children]
    frontend
    backend